# Generated by Django 4.0 on 2021-12-14 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0002_monthly_shipinstr_shipment_shipinstr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monthly',
            name='material',
            field=models.TextField(max_length=50),
        ),
    ]
