# Generated by Django 4.0 on 2021-12-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0004_alter_monthly_eta_alter_monthly_etd_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='material',
            field=models.TextField(max_length=50),
        ),
    ]
