# Generated by Django 3.2.7 on 2021-12-14 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0005_alter_track_material'),
    ]

    operations = [
        migrations.AlterField(
            model_name='so',
            name='comment',
            field=models.TextField(max_length=1000),
        ),
    ]
