# Generated by Django 4.0 on 2021-12-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0005_alter_track_material'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='equip',
            field=models.CharField(default=1, max_length=30),
            preserve_default=False,
        ),
    ]
