# Generated by Django 3.2.8 on 2022-01-30 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inputs', '0008_alter_so_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buffer',
            name='ETA',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='buffer',
            name='ETD',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='buffer',
            name='Origin',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='buffer',
            name='bknumber',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='buffer',
            name='carrier',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='buffer',
            name='comment',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='buffer',
            name='number',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='buffer',
            name='proveedor',
            field=models.TextField(max_length=500),
        ),
    ]
